// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en":    &dictionary{index: enIndex, data: enData},
		"pt_BR": &dictionary{index: pt_BRIndex, data: pt_BRData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%.f":                           0,
	"Are we alone in the Universe?": 6,
	"Astronomy Education":           1,
	"Create Session":                12,
	"Drake Equation":                5,
	"Estimate the number of detectable alien civilizations in the Milky Way using the Drake Equation.": 7,
	"Home":                  4,
	"Internal Server Error": 2,
	"Join Session":          13,
	"Learning Goals:":       8,
	"Page Not Found":        3,
	"to compare your initial guess with the final value":                                                           11,
	"to think about the size and composition of the galaxy and how it affects the possibility of intelligent life": 9,
	"to understand and estimate the terms of the Drake Equation":                                                   10,
}

var enIndex = []uint32{ // 15 elements
	0x00000000, 0x00000007, 0x0000001b, 0x00000031,
	0x00000040, 0x00000045, 0x00000054, 0x00000072,
	0x000000d3, 0x000000e3, 0x00000150, 0x0000018b,
	0x000001be, 0x000001cd, 0x000001da,
} // Size: 84 bytes

const enData string = "" + // Size: 474 bytes
	"\x02%.[1]f\x02Astronomy Education\x02Internal Server Error\x02Page Not F" +
	"ound\x02Home\x02Drake Equation\x02Are we alone in the Universe?\x02Estim" +
	"ate the number of detectable alien civilizations in the Milky Way using " +
	"the Drake Equation.\x02Learning Goals:\x02to think about the size and co" +
	"mposition of the galaxy and how it affects the possibility of intelligen" +
	"t life\x02to understand and estimate the terms of the Drake Equation\x02" +
	"to compare your initial guess with the final value\x02Create Session\x02" +
	"Join Session"

var pt_BRIndex = []uint32{ // 15 elements
	0x00000000, 0x00000000, 0x00000019, 0x00000032,
	0x0000004a, 0x00000052, 0x00000064, 0x00000082,
	0x000000eb, 0x00000105, 0x00000167, 0x0000019a,
	0x000001c9, 0x000001d7, 0x000001e8,
} // Size: 84 bytes

const pt_BRData string = "" + // Size: 488 bytes
	"\x02Educação em Astronomia\x02Erro Interno do Servidor\x02Página Não Enc" +
	"ontrada\x02Início\x02A Equação Drake\x02Estamos sozinhos no Universo?" +
	"\x02Estime o número de civilizações alienígenas detectáveis na Via Lácte" +
	"a usando a Equação de Drake.\x02Objetivos de Aprendizado:\x02pensar sobr" +
	"e o tamanho e composição da galaxia e como afeta a possibilidade de vida" +
	" inteligente\x02entender e estimar os termos da Equação de Drake\x02comp" +
	"arar seu palpite inicial com o valor final\x02Criar Sessão\x02Entra na S" +
	"essão"

	// Total table size 1130 bytes (1KiB); checksum: C175546D
